// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/joho/godotenv"
	"github.com/lyleshaw/open-plugin/biz/dal"
	"github.com/lyleshaw/open-plugin/biz/mw"
	"os"
)

func main() {
	_ = godotenv.Load(".env")

	dal.Init()
	port := ":" + os.Getenv("PORT")
	h := server.New(server.WithHostPorts(port))
	h.Use(mw.Cors())
	register(h)
	h.Spin()
}
