// Code generated by hertz generator.

package Service

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getchatMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _postchatMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getpluginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _postpluginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletepluginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getpluginsMw() []app.HandlerFunc {
	// your code...
	return nil
}
