// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package orm_gen

import (
	"time"
)

const TableNameChat = "Chats"

// Chat mapped from table <Chats>
type Chat struct {
	ChatID         int32     `gorm:"column:chat_id;primaryKey;autoIncrement:true;comment:Unique identifier for the chat" json:"chat_id"`
	ConversationID string    `gorm:"column:conversation_id;not null;comment:Unique identifier for the conversation that the chat belongs to" json:"conversation_id"`
	PluginNames    string    `gorm:"column:plugin_names;not null;comment:Array of plugin names used in the chat" json:"plugin_names"`
	ChatContent    string    `gorm:"column:chat_content;comment:Content of the chat message" json:"chat_content"`
	ChatModel      string    `gorm:"column:chat_model;comment:Model for the chat message" json:"chat_model"`
	UserID         int32     `gorm:"column:user_id;not null;comment:Unique identifier for the user who sent the chat message" json:"user_id"`
	IsDeleted      bool      `gorm:"column:is_deleted;not null;comment:Flag indicating if the chat message has been deleted" json:"is_deleted"`
	CreatedAt      time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:Timestamp for when the chat message was created" json:"created_at"`
	UpdatedAt      time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:Timestamp for when the chat message was last updated" json:"updated_at"`
}

// TableName Chat's table name
func (*Chat) TableName() string {
	return TableNameChat
}
